development:
  host: '127.0.0.1'
  port: 9042
  keyspace: cequel_auth_development

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: cequel_auth_test

production:
  hosts:
    - 'cass1.cequel_auth.biz'
    - 'cass2.cequel_auth.biz'
    - 'cass3.cequel_auth.biz'
  port: 9042
  keyspace: cequel_auth_production
  username: 'myappuser'
  password: 'password1'
